### ISSUE TITLE
[Android] - java.lang.NoClassDefFoundError: Failed resolution of: Lcom/braintreepayments/api/BraintreeFragment

### ISSUE THREAD

**Issue by mrmello** [smarkets/react-native-paypal#22]
Hi, I'm getting the `Exception in HostObject::get: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/braintreepayments/api/BraintreeFragment;` on Android. I didn't setup iOS yet.
It happens whenever I try to call the `requestOneTimePayment`.

I did:
- `yarn add react-native-paypal`
- `react-native link react-native-paypal`
- `react-native run-android`

Also tried the manual steps shown for android, but the error persists.

here is the peace I'm trying to exectue:
```
import React, { PureComponent } from 'react';
import { View } from 'react-native';
import { requestOneTimePayment } from 'react-native-paypal';
import Button from '../button/Button';

class PayPal extends PureComponent {
  handlePayPal = async () => {
    const token = 'TOKEN';
    // Request Payment with Token
    const { nonce } = await requestOneTimePayment(token, {
      amount: '250', // required
      // any PayPal supported currency (see here: https://developer.paypal.com/docs/integration/direct/rest/currency-codes/#paypal-account-payments)
      currency: 'USD',
      // any PayPal supported locale (see here: https://braintree.github.io/braintree_ios/Classes/BTPayPalRequest.html#/c:objc(cs)BTPayPalRequest(py)localeCode)
      localeCode: 'en_US',
      shippingAddressRequired: false,
      userAction: 'commit', // display 'Pay Now' on the PayPal review page
      // one of 'authorize', 'sale', 'order'. defaults to 'authorize'. see details here: https://developer.paypal.com/docs/api/payments/v1/#payment-create-request-body
      intent: 'authorize',
    });
    console.log(nonce)
  };

  render() {
    return (
      <View>
        <Button onPress={this.handlePayPal} label="PAYPAL" />
      </View>
    );
  }
}

export default PayPal;
```

<img width="360" alt="Screenshot 2019-07-19 at 17 22 18" src="https://user-images.githubusercontent.com/4693051/61563560-a2f86380-aa4a-11e9-9248-13dddfabe51f.png">

Can someone help me with this?
Thanks in advance!

**Comment by mrmello** [comment]
Fixed!
Forgot to execute step 2 of the readme

**Comment by vohoangankhanh** [comment]
I have the same issue, my react-native version is 0.61.5, which doesn't need to link library, but I get this error, now I link manually still getting this error, please help

**Comment by jothikannan** [comment]
@vohoangankhanh I am also getting the same error

**Comment by crzycoder** [comment]
add `implementation "com.braintreepayments.api:braintree:2.17.0"` in user android/app/build.gradle

**Comment by rohitpatil8195** [comment]
i am getting same error...doed anyone knows the solution?

**Comment by nzankich** [comment]
@rohitpatil8195 do you have the braintree sdk in your `build.gradle` file?

This is step 2 in the instructions:
2. [Android] Add implementation "com.braintreepayments.api:braintree:3.14.1" in android/app/build.gradle.
