### ISSUE TITLE
[ANDROID] Promise is not resolving on second time paying.

### ISSUE THREAD

**Issue by dkfl1995** [smarkets/react-native-paypal#67]
Hi guys.
Few days ago started with upgrading BT SDK from 2.17 to latest 3.14.2 as faced Google Play team warning like related to this [issue](https://github.com/smarkets/react-native-paypal/issues/52).
Found really disgusting issue right there then after upgrading. If you use like new 3.14.2 BT SDK version promise on `requestOneTimePayment` native method still remains the same each time you trigger this method. This lead to promise to be useless as it won't run `resolve` or `reject` on second request and then. HashCode of promise still remains the same. As on BT SDK v2.17 promise has different HashCode each time you trigger `requestOneTimePayment` method.

**Comment by krupalikevadiya** [comment]
Yes found same issue in android only.Have you found any solution for it?

**Comment by dkfl1995** [comment]
@krupalikevadiya  actually, having a talk with PayPal development team so they researching this issue. Once I will get any response, will write right there

**Comment by valerio-fornace** [comment]
Are there any kind of news about this issue?

**Comment by nzankich** [comment]
@valerio-fornace  There's an open MR that needs a tweak but it should be ready to go after that.  If I don't get a response for a few days I'll finish up the fix and do a release

**Comment by valerio-fornace** [comment]
@nzankich thanks this is a good news!

**Comment by nzankich** [comment]
fixed on 4.0.1

be sure to follow the upgrade instructions for 4.0.0 https://github.com/smarkets/react-native-paypal/releases/tag/4.0.0

**Comment by Talha-Jawed** [comment]
@nzankich 
still getting same issue in android.

`"react-native": "0.64.2",`
`"react-native-paypal": "4.1.0",`
